language: node_js
node_js:
  - "14"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=7000 GMAIL_USER=tdn.social.network@gmail.com GMAIL_PASSWORD=socialnetwork
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - nohup npm run start &
  - sleep 3
  - bash mocha.sh type=full
